# Generated by Django 4.1.3 on 2022-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0022_auto_20221111_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(max_length=100, to='message.service'),
        ),
    ]
